### ISSUE TITLE
Add support for user to set preferred audio quality

### ISSUE THREAD

**Issue by jcass77** [rectalogic/mopidy-pandora#1]
Pandora provides more than one audio URL for certain devices (e.g. android-generic), which contain different bitrate encodings.

It should ideally be possible for the user to specify their preferred bitrate, especially in situations where Mopidy is used with high fidelity audio equipment. I've created a fork here to start implementing this functionality:

https://github.com/jcass77/mopidy-pandora.git

Please take a look at the code to see if this is something that you think could work? This code is dependent on the related pydora pull request: https://github.com/mcrute/pydora/pull/2

Thanks for starting the mopidy-pandora plugin!

**Comment by jcass77** [comment]
I've created the pull request so long (https://github.com/rectalogic/mopidy-pandora/pull/3)

**Comment by jcass77** [comment]
Just a note that the required changes to pydora were recently merged, and are now contained in release 0.2.3.

@rectalogic, would you mind taking a look at https://github.com/rectalogic/mopidy-pandora/pull/3 when you are ready and let me know if you encounter any issues?

**Comment by rectalogic** [comment]
Merged #3

**Comment by jcass77** [comment]
I forgot to increment the required version number of pydora - please take a look at https://github.com/rectalogic/mopidy-pandora/pull/5
