### ISSUE TITLE
Music stops playing after 2-3 songs.

### ISSUE THREAD

**Issue by jrlambs** [rectalogic/mopidy-pandora#48]
First I'll start this by saying I'm working with a non-standard configuration.

I started with a MusicBox Image which I wanted to run on a pi3.  I manually updated some of the boot files and got it to boot up.. then updated the repositories to jessie repositories and ran apt-get update/upgrade on everything... then I installed the newest firmware with rpi-update.  After that musicbox appeared to start up and run normally.  

Then I attempted an install of mopidy-pandora.. which made musicbox not work every time I tried until I realized it was installing mopidy 2.0 which wasn't working right due to other things missing.  anyway.  I finally had success.  I installed the dev-tools needed and then updated mopidy and installed pydora and mopidy-pandora.  this has left me with the following versions of things.  full list at the very bottom of this text.

pydora (1.7.0)
Mopidy-Pandora (0.1.8)
cachetools (1.0.0)
requests (2.5.1)

The issue I'm having is this.  I click a pandora station and it lists one "Track" (which also has the name of that pandora station).  I click the track and it starts playing.  As each song plays in the log I get 2 lines that look like this:
Up next: 'The Killing Moon' by Echo & The Bunnymen
WARNING  Element doesn't implement handling of this stream. Please file a bug.

repeat does not appear as though it gets turned on no its own... though I can hit the button and turn it on when it starts

the music plays fine for a song or two.. at which point it just stops at the end of a song.  this error shows in the log:

`2016-04-11 20:19:53,927 - INFO     Up next: 'Gonna Find You' by Operation Ivy
2016-04-11 20:19:54,066 - WARNING  Element doesn't implement handling of this stream. Please file a bug.
2016-04-11 20:20:22,648 - INFO     200 GET / (127.0.0.1) 2.59ms
2016-04-11 20:21:49,098 - ERROR    Triggering event failed: reached_end_of_stream
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/listener.py", line 55, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 243, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 208, in _change_track
    self._play(on_error_step=on_error_step)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/playback.py", line 359, in _play
    backend.playback.change_track(tl_track.track).get() and
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/playback.py", line 63, in change_track
    next_track = self.get_next_track(track_uri.index)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/playback.py", line 87, in get_next_track
    logger.warning("Track with uri '%s' is not playable.", TrackUri.from_track(track).uri)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/uri.py", line 83, in from_track
    return TrackUri(track.station_id, track.track_token, track.song_name, track.song_detail_url,
AttributeError: 'AdItem' object has no attribute 'track_token'
`

Side Note:  if I update mopidy-pandora to v0.2.0 and click on a station the track title actually looks like a track.. not just the title of the station.. but clicking on it gives me the error: 
`2016-04-11 20:31:57,760 - ERROR    PandoraBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 236, in lookup
    result = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/library.py", line 85, in lookup
    track_kwargs['bitrate'] = int(track.bitrate)`

**Comment by jcass77** [comment]
I don't think Mopidy-Pandora 0.1.8 is compatible with pydora 1.7.0. I'd try to revert to pydora 1.5.1 on that setup as a first step to see if that works (ad token handling changed a lot in the later versions).

Support for the `bitrate` field was added in pydora 1.6.1 so I'm not sure why you would experience issues with this in Mopidy-Pandora 0.2.1 if you have pydora 1.7.0 installed.

All of the above sounds suspiciously like version conflicts between Mopidy-Pandora and pydora. Perhaps you can try running `pip uninstall` multiple times on each until pip reports that there is nothing more to uninstall (especially if you ran `python setup.py install` or `develop` before), and start again.

**Comment by jrlambs** [comment]
I'll need to play with it some tonight, but last night I attempted a complete system overhaul starting fresh with a clean raspbian image.  I installed the devel environment and pip I believe via apt-get as well as gstreamer 1.0 and all of its related items.  Then I installed mopidy, pydora, mopidy-pandora via pip.. just letting everything install their default version.. ended up with pydora 1.7.0, mopidy-pandora 0.2.1 and mopidy 2.0.0.  I had a few issues along the way.. for one I know I had to roll back certifi to (2015.4.28) due to an error when trying to play pandora... and I needed to roll back mopidy-pandora to 0.1.8 but ended up with about the same setup as before... the only difference being now when I get the  'AdItem' object has no attribute 'track_token'  error it appears to get the "Bad Track" message right after and move on to the next track successfully.  Incidentally I get the exact same issue when I use mydora 1.7.0 and mopidy-pandora 0.2.0/0/2.1

**Comment by jcass77** [comment]
Could you elaborate on why it was necessary "...to roll back mopidy-pandora to 0.1.8..."? 

The certifi version incompatibility is a known issue and downgrading to 2015.4.28 should not cause any problems (I've been running that version for close to a year now).

Apart from that, using the latest versions of everything would be preferable. But I think there may be a range of incompatibilities between Pi3, the Pi Musicbox, and gstreamer 1.0 which have not been fully explored yet (I know I am waiting for some sort of official support before attempting an upgrade such as this).

So you may be blazing a trail through some new territory here - let me know how it goes.

**Comment by jrlambs** [comment]
mainly I had to roll back to 0.1.8 because I was getting the same issue described above when using v 0.2.0 or 0.2.1.. which was the error with this in it:

"/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop response = self._handle_receive(message) File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive return callee(*message['args'], **message['kwargs']) File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/library.py", line 85, in lookup track_kwargs['bitrate'] = int(track.bitrate)

incidentally I got a few minutes and logged into home and tested this configuration and it appears to play continuously with no errors in the log... so you were right-on with saying to go back to pydora 1.5.1.. I think i had tried 1.6 without luck before.

All of this below was done on a "Fresh" image of raspbian, not the one that I upgraded from the musicbox image.

 Mopidy (2.0.0)
 pydora (1.5.1)
 Pykka (1.2.1)
 certifi (2015.4.28)
 Mopidy-Pandora (0.1.8)
 gstreamer 1.0

after that was working I uninstalled mopidy-pandora and pydora and installed the lastest version of each.. so my configuration is now:

 Mopidy (2.0.0)
 pydora (1.7.0)
 Pykka (1.2.1)
 certifi (2015.4.28)
 Mopidy-Pandora (0.2.1)
 gstreamer 1.0

with this configuration I'm able to list the stations, click on a station and see a song name.. but as soon as I click on the song name to play it I get the exception below.

ERROR    PandoraBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 19,in _backend_error_handling
    yield
  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/library.py", line 236, in lookup
    result = future.get()
  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_pandora/library.py", line 85, in lookup
    track_kwargs['bitrate'] = int(track.bitrate)
TypeError: int() argument must be a string or a number, not 'NoneType'

Incidentally that's the same error I got when I had mopidy 1.x with gstreamer 0.1 on the old musicbox image.

Thanks for your help getting through this.. and we may not come to a solution.. but I'm fairly new to the python/pip world so I'm muttling through.. at least I have a working solution of some sort that I can use.

**Comment by jcass77** [comment]
The exception in the log file suggests that you are getting playlists back in which the `bitrate` field is not populated, which is contrary to our current understanding of the Pandora API: https://6xq.net/pandora-apidoc/json/play/#retrieve-playlist.

Are you sure that you do now somehow have old pydora .pyc files floating around? The `bitrate` field was only introduced in version 1.6.1 as I mentioned above so that would explain it.

If you are confident that that is not the cause then we could probably add some exception handling in the code to avoid this type of issue in the future.

**Comment by jcass77** [comment]
I've create PR #49 which you could also try if you are still experiencing problems.

Please report back if this resolves the issue for you and we can then release a new version containing the fix.

**Comment by jrlambs** [comment]
I'll check it out.. where would the _old_ pydora files be if they were hanging out?  I'm logged in as root to the machine so I'm not sure where the files land when I run install.  I _did_ run uninstall of the old one before installing the new one and when it completed I ran uninstall again.. which informed me that the module was not present and could not be uninstalled.  I'll try the version with your commit in it tonight to see if that does it.

**Comment by jrlambs** [comment]
I applied your patch and it does indeed fix the issue.  There are no messages in the log to indicate any issues...

I'm successfully running 
pydora 1.7 + gstreamer 1.0 + mopidy-pandora 0.2.1 including your patch + mopidy 2.0.0.

it's still very odd to me.. I'm using a free pandora account.. like there's something special about the account causing it to not send bitrate or something.. no clue.  I searched and removed every file and directory called pydora and tried it with the new versions without the patch and no luck with that... so def something weird going on.. but the patch works.

just as a last ditch effort.. here's my config.. maybe I have something weird in there that is causing the bitrate to get dropped? wrong URL or preferredBitrate or something?

enabled = true
api_host = tuner.pandora.com/services/json/
partner_encryption_key = 721^26xE22776
partner_decryption_key = 20zE1E47BE57$51
partner_device = IP01
partner_username = iphone
partner_password = P2E4FC0EAD3*878N92B2CDp34I0B1@388137C
preferred_audio_quality = mediumQuality
username = *************
password = ***************

**Comment by jcass77** [comment]
Thank you for taking the time to troubleshoot this.

There's a `*` missing in the `partner_password` string in your config file, but I'm going to assume that is just a copy / paste artefact as the backend would not have started up otherwise.

In debugging this some more, it appears that streams for the `IP01` partner only contains one audio URL instead of the usual three, and does not provide a bitrate either.

So this is a perfectly valid usecase that we have not provided for before. I'll merge the PR and add a note in the docs to highlight this - thank you.

P.S. it might be worth considering using the `android` partner settings instead as this will afford you some level of control over the stream quality via `preferred_audio_quality`, which it now seems has no effect for `IP01`.

**Comment by jrlambs** [comment]
Ah, this makes perfect sense.  I'm a programmer by trade and I personally hate it when I have to put in a fix for a bug I don't fully understand... so I was happy to keep digging for the root cause.  Thanks a lot for all of your help.

Side note:  if I go to "Edit" the post above with the partner password.. the `*` is there... i probably should have pasted that as code so it wouldn't interpret that as markup and eat the *

Thanks!
