### ISSUE TITLE
Disable search in mopidy-pandora

### ISSUE THREAD

**Issue by rishipi** [rectalogic/mopidy-pandora#57]
Hi,

Is there anyway I can disable Pandora's search function? I want Mopidy-Touchscreen to be the only search function.

**Comment by jcass77** [comment]
I'm not sure I understand the question - the frontend extension (i.e. Mopidy-Touchscreen) controls which backend's search function to call.

If you only want to perform searches on specific backend libraries, then that type of filtering is usually a feature provided in the frontend (e.g. Mopidy-Musicbox-Webclient does this).

Disabling searching on the backend is not supported by the Mopidy API.
