### ISSUE TITLE
Is the installer ready for users?

### ISSUE THREAD

**Issue by salamanders** [rectalogic/mopidy-pandora#6]
I read the part about how you have to loop a single track playlist, am OK with that.
I tried installing via `pip install Mopidy-Pandora` but it eventually timed out.  Do I need to add any special repositories, or pull directly from github somehow?

**Comment by rectalogic** [comment]
It's not published to pypi, you could just do `pip install https://github.com/rectalogic/mopidy-pandora/zipball/master`

**Comment by salamanders** [comment]
Worked like a charm, trying it out now, thank you!

**Comment by sjwgator** [comment]
I tried this and got an error about pycrypto -- it says that "--single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/pycrypto".  Is there something I'm not doing correctly to install this?

**Comment by rectalogic** [comment]
pydora depends on pycrypto, can you `pip install pydora`?

**Comment by sjwgator** [comment]
I tried running `pip install pydora` and I think I found the reason nothing is installing properly.  It looks like the errors are related to gcc.  It couldn't find the compiler.  So I installed using `apt-get install gcc`.  gcc-4.6 was installed and I tried again, but I got the error "configure: error: C complier cannot create executables".  I saw some solutions on upgrading to gcc-4.7, but that didn't seem to work either.  Any thoughts?

**Comment by rectalogic** [comment]
Try `sudo apt-get install build-essential python-dev`

**Comment by sjwgator** [comment]
Awesome.  That worked.  Thanks for the help!

**Comment by sjwgator** [comment]
One more question.  I got mopidy-pandora installed, updated my mopidy.conf file with the Pandora settings and when I reboot the Raspberry Pi I get an error of an "unknown config key" for the musicbox_webclient.  I need the webclient to run and I've searched for solutions to the issue but have come up empty.

**Comment by rectalogic** [comment]
Did you upgrade mopidy itself as part of this? I think musicbox needs an older version of mopidy, but I don't know anything about musicbox.
https://discuss.mopidy.com/t/using-mopify-with-pi-musicbox/692/4

If you upgraded mopidy, then maybe upgrade musicbox `pip install Mopidy-MusicBox-Webclient`

**Comment by jcass77** [comment]
I can confirm that Mopidy-Pandora works with the Pi MusicBox. Like @rectalogic said, the error message is probably related to version dependencies between Mopidy and the webclient.

I have ```Mopidy (1.0.5)``` and ```Mopidy-MusicBox-Webclient (2.0.0)```, but the stock versions that come with the standard MusicBox distribution also works.

**Comment by sjwgator** [comment]
Excellent.  So what was your process @jcass77? Install Pi MusicBox 0.6, upgrade to `Mopidy 1.0.5` and upgrade to `Mopidy-MusicBox-Webclient 2.0.0`?  For some reason I couldn't get it working with the stock version.  I kept running into the errors above.

**Comment by jcass77** [comment]
I started with the stock PI MusicBox 0.6. Does Mopidy start up and can you access the web client at this point? Once that is running you can look at installing Mopidy-Pandora:

* Probably ```apt-get update; apt-get --yes install automake build-essential python-dev```

* ```pip install pydora Mopidy-Pandora```

You can optionally upgrade Mopidy and Mopidy-MusicBox-Webclient as well, but the stock versions work with Mopidy-Pandora just fine.

Perhaps there is a problem with the mopidy configuration file that you are using? If you can post it here we can perhaps take a look?

**Comment by sjwgator** [comment]
I started all over, followed these posts again and got it working.  I must have misstepped somewhere in the process.  It's up and running now.  Thank you both for all of your help.  Now if there were only a mopidy-iheartradio I would be golden.  This will do really well however.  It's working great!
