### ISSUE TITLE
Station start but plays only few seconds

### ISSUE THREAD

**Issue by kdjordjev** [rectalogic/mopidy-pandora#64]
Hello
i am having the following issue.

Many times when i click on the station, it starts but plays only few seconds (~5s) and then stops and loops back from the beginning. I can see the progress bar starting counting to ~ 5s and starting back from 0.
I have to press "Next Track" button for the same station few times to start the next song and make it play.

Please let me know if someone have seen this behavior.
Also any suggestions on how to debug it, fix the issue.

Thanks

**Comment by jcass77** [comment]
Sounds like a network / buffering issue. Have you looked at the [troubleshooting guide](https://github.com/rectalogic/mopidy-pandora/blob/develop/docs/troubleshooting.rst)?

**Comment by kdjordjev** [comment]
@jcass77 Thank you for being willing to help.
Below is a log file. From what i see I am getting an errors "GStreamer: No volume control found (3)" and " Track is not playable:", "GStreamer error: Could not write to resource"

Description of events below. Thanks in advance.



It seems every time i start Pandora station and I got the Gstreamer warning , the playback is stalled.


> 2018-06-21 07:25:32,517 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora track pandora:track:3974224353236493660:PC4SkPh6Px6yRQVT5RTNeLoT1E2M4XcaJ1Oa1wNdpYk1PZY3LQOhG1roXTtgmA_5xidtxiwZO-G3CyjP72cBr6w...
2018-06-21 07:25:44,460 WARNING [22512:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No volume control found (3)
2018-06-21 07:25:44,526 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora track pandora:track:3974224353236493660:Pa-0BRsiNLiyRQVT5RTNeLsrxR9nns4EJ1Oa1wNdpYk1PZY3LQOhG1up2whQ24wjdidtxiwZO-G12_AhqvUl_Eg...

The playback is stalled after this. I need to press "next track button". then the playback may start again. I get a log entry. Interestingly the log entry shows "ad", but the playback is a music track

> 2018-06-21 07:29:16,659 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora ad pandora:ad:3974224353236493660:3974224353236493660-pod%3A1/2/1...

After the music track is over , i get a playback of the ad. But after the ad is over i get an error: "Changing pandora Track" and "track is not playable" 

> 2018-06-21 07:32:54,682 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora ad pandora:ad:3974224353236493660:3974224353236493660-pod%3A2/2/1...
2018-06-21 07:33:14,031 WARNING [22512:PandoraBackend-4] mopidy_pandora.playback: Error changing Pandora track: Track(album=Album(name=u'(Company name not specified)', uri='pandora:ad:3974224353236493660:3974224353236493660-pod%3A2/2/1'), artists=[Artist(name=u'(Title not specified)', uri='pandora:ad:3974224353236493660:3974224353236493660-pod%3A2/2/1')], name=u'Advertisement', uri='pandora:ad:3974224353236493660:3974224353236493660-pod%3A2/2/1'), (Track with URI 'pandora:ad:3974224353236493660:3974224353236493660-pod%3A2/2/1' is not playable.)
2018-06-21 07:33:14,033 WARNING [22512:Core-10] mopidy.core.tracklist: Track is not playable: pandora:ad:3974224353236493660:3974224353236493660-pod%3A2/2/1
2018-06-21 07:33:14,097 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora track pandora:track:3974224353236493660:PLDOlpjju06ORQVT5RTNeLugi-TOWSkPt1Oa1wNdpYk1PZY3LQOhG1v2FI6Y-v39xaFyM7i7YNzDJ-KylVk6S3w...
2018-06-21 07:33:14,307 WARNING [22512:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No volume control found (3)
2018-06-21 07:33:14,365 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora track pandora:track:3974224353236493660:PoNOLkC3yEXCRQVT5RTNeLr4d9pDDpWXP1Oa1wNdpYk1PZY3LQOhG1hVuh5rWi-OPaFyM7i7YNzDlnu-yEEmkow...

In order to resume I have to press the "Next Track " button again. This time i got a track entry

> 2018-06-21 07:37:03,864 INFO [22512:PandoraBackend-4] mopidy_pandora.library: Looking up Pandora track pandora:track:3974224353236493660:PNTG355INpSuRQVT5RTNeLprmpYHZEXMk1Oa1wNdpYk1PZY3LQOhG1oN78y0ujdp3XXb0-8Ay-pQCrtB-sH3g_g...

**Comment by jcass77** [comment]
The```Track is not playable``` log entries should not pose too much of a problem as mopidy-pandora automatically skips to the next track.

I think the problem is rather with Gstreamer. How did you install Mopidy and mopidy-pandora?

Do you experience any problems with any of the other Mopidy back-ends? (e.g. Spotify, TuneIn, or local files?)

**Comment by kdjordjev** [comment]
I have them installed on a Synology NAS station under DebianChroot.
Followed all procedures outlined in the writeups
I stream the audio through shout2send to icecast. Then using the mopidy.mp3 stream to play on remote devices (Sonos, Chromecasts)

I do not have any issues with playing local files.  It is robust
However playing internet stations through Pandora do not work reliably. Need to press "NextStation" few time to get it started.

I also installed TuneIn this morning and seems i get the same Gstremer warning. Sometimes has issues, but seems relatively stable so far

I do not have Spotify

> [pandora]
enabled = true
api_host = tuner.pandora.com/services/json/
partner_encryption_key = 6#26FRL$ZWD
partner_decryption_key = R=U!LH$O2B#
partner_username = android
partner_password =  AC7IBG09A3DTSYM4R41UJWL07VLN8JI7
partner_device = android-generic
username = xxxxx
password = xxxxxx
auto_setup = true

> [audio]
mixer = software
output = lamemp3enc ! shout2send mount=mopidy.mp3 ip=127.0.0.1 port=8000 passwo$



> 2018-06-21 15:23:42,875 WARNING [22512:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No volume control found (3)

**Comment by jcass77** [comment]
Sorry I may be fresh out of ideas. Only other thing I can think of would be to confirm that you have installed all of the GStreamer plugins (good, bad, ugly).

If you have been skipping a bunch of tracks by clicking ‘Next’ then it could also be that the Pandora service is blocking / throttling your account.

Have you tried using pydora directly as per the troubleshooting guide?

**Comment by kdjordjev** [comment]
Thank you for helping in this.

It turns out I had some issue with the install of the gstremer on the synology
- i did a fresh install on Rassbery pi and seems it was functional without the same issue
- then i came back to the Synology and upgraded the distribution from Jesse to Stretch. Now i do not see the "Gstreamer no volume control issue". 

It works much better , but still I am having glitches from time to time. " GStreamer error: gst-resource-error-quark: Could not write to resource.". It seems to happen more often after the ads, when the plugin generates warnings/errors " track is not playable."

Anyway.. will close the issue
Thanks a lot
